apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: rukpak-system
  name: helm-provisioner
  labels:
    app: helm-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm-provisioner
  template:
    metadata:
      labels:
        app: helm-provisioner
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: helm-provisioner-admin
      containers:
        - name: kube-rbac-proxy
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ "ALL" ]
          image: quay.io/brancz/kube-rbac-proxy:v0.12.0
          args:
            - "--secure-listen-address=0.0.0.0:8443"
            - "--upstream=http://127.0.0.1:8080/"
            - "--logtostderr=true"
            - "--v=1"
            - "--client-ca-file=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
          ports:
            - containerPort: 8443
              protocol: TCP
              name: https
          resources:
            requests:
              cpu: 1m
              memory: 15Mi
        - name: manager
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ "ALL" ]
          image: quay.io/operator-framework/rukpak:devel
          imagePullPolicy: IfNotPresent
          command: ["/helm"]
          args:
            - "--unpack-image=quay.io/operator-framework/rukpak:devel"
            - "--base-upload-manager-url=https://$(CORE_SERVICE_NAME).$(CORE_SERVICE_NAMESPACE).svc"
            - "--storage-dir=/var/cache/bundles"
            - "--http-bind-address=127.0.0.1:8080"
            - "--http-external-address=https://$(HELM_PROVISIONER_SERVICE_NAME).$(HELM_PROVISIONER_SERVICE_NAMESPACE).svc"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 10m
              memory: 160Mi
