apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: rukpak-system
  name: core
  labels:
    app: core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core
  template:
    metadata:
      labels:
        app: core
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      serviceAccountName: core-admin
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: kube-rbac-proxy
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ "ALL" ]
          image: quay.io/brancz/kube-rbac-proxy:v0.12.0
          args:
            - "--secure-listen-address=0.0.0.0:8443"
            - "--upstream=http://127.0.0.1:8080/"
            - "--logtostderr=true"
            - "--v=1"
            - "--client-ca-file=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
          ports:
            - containerPort: 8443
              protocol: TCP
              name: https
          volumeMounts: []
          resources:
            requests:
              cpu: 1m
              memory: 15Mi
        - name: manager
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ "ALL" ]
          image: quay.io/operator-framework/rukpak:devel
          imagePullPolicy: IfNotPresent
          command: ["/core"]
          args:
            - "--unpack-image=quay.io/operator-framework/rukpak:devel"
            - "--base-upload-manager-url=https://$(CORE_SERVICE_NAME).$(CORE_SERVICE_NAMESPACE).svc"
            - "--provisioner-storage-dir=/var/cache/bundles"
            - "--upload-storage-dir=/var/cache/uploads"
            - "--http-bind-address=127.0.0.1:8080"
            - "--http-external-address=https://$(CORE_SERVICE_NAME).$(CORE_SERVICE_NAMESPACE).svc"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: bundle-cache
              mountPath: /var/cache/bundles
            - name: upload-cache
              mountPath: /var/cache/uploads
          resources:
            requests:
              cpu: 10m
              memory: 160Mi
      volumes:
        - name: bundle-cache
          emptyDir: {}
        - name: upload-cache
          emptyDir: {}
